# Requirement: Development Environment - Local development environment setup with Docker containers
version: '3.8'

# Requirement: Frontend Stack - React Native web development environment configuration
services:
  # Web dashboard development service with hot-reloading and debugging enabled
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
      args:
        - NODE_ENV=development
        - NEXT_TELEMETRY_DISABLED=1
    
    # Requirement: Containerization - Development container configuration with hot-reloading
    ports:
      # Next.js development server port
      - "3000:3000"
      # Node.js inspector protocol for debugging
      - "9229:9229"
    
    # Requirement: Development Environment - Source code mounting for hot reloading
    volumes:
      # Mount source code for development
      - ../:/app:delegated
      # Persistent node_modules volume for better performance
      - node_modules:/app/node_modules
    
    # Development environment variables
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api/v1
      - NEXT_PUBLIC_WS_URL=ws://localhost:3000
      - NEXT_PUBLIC_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    
    # Requirement: Development Environment - Container health checks
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Development network configuration
    networks:
      - pantrychef-dev
    
    # Container resource limits for development
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

# Requirement: Containerization - Persistent storage for dependencies
volumes:
  # Node modules volume for dependency caching
  node_modules:
    name: pantrychef-web-node-modules
    driver: local

# Requirement: Development Environment - Isolated network for services
networks:
  # Development network for service communication
  pantrychef-dev:
    driver: bridge
    name: pantrychef-dev
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16