# SwiftLint configuration for PantryChef iOS app
# Version: 0.50.0

# HUMAN TASKS:
# 1. Review and adjust line length limits if needed for specific files
# 2. Validate custom rules against team's coding standards
# 3. Update excluded paths if new test directories are added
# 4. Verify theme_usage rule exceptions for system color usage in Theme.swift

# Disabled rules that conflict with the project's style or create noise
disabled_rules:
  - trailing_whitespace
  - vertical_whitespace_opening_braces

# Opt-in rules for enhanced code quality and consistency
opt_in_rules:
  - force_unwrapping
  - private_outlet
  - prohibited_interface_builder
  - private_action
  - file_header
  - explicit_init
  - closure_spacing
  - unneeded_parentheses_in_closure_argument

# Paths to ignore during linting
excluded:
  - Pods
  - PantryChefTests
  - PantryChefUITests
  - fastlane

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 400
  error: 1000
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

function_parameter_count:
  warning: 5
  error: 7

nesting:
  type_level:
    warning: 2
    error: 3

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - url
    - key
    - tag
    - app
    - raw
    - get
    - set

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

# Custom rules for project-specific requirements
custom_rules:
  theme_usage:
    name: "theme_usage"
    regex: "UIColor\\(|UIFont\\(|CGColor\\(|systemBackground|systemFill"
    message: "Use Theme class for colors and fonts to maintain consistent styling"
    severity: warning

  constants_usage:
    name: "constants_usage"
    regex: "\"[^\"]*API|\"[^\"]*URL|\"[^\"]*Token|\"[^\"]*Key"
    message: "Use Constants for API, URL, and security-related values"
    severity: warning

  analytics_tracking:
    name: "analytics_tracking"
    regex: "\"[^\"]*Event|\"[^\"]*Track|\"[^\"]*Metric"
    message: "Use Analytics constants for tracking event names and metrics"
    severity: warning